### ISSUE TITLE
How to build ios?

### ISSUE THREAD

**Issue by uokivan** [hankinsoft/FreeTDS#2]
Dear hankinsoft,

I can use the project build succeeded on xcode,
but why can't install to my iphone ?

Thank you very much
Ivan

**Comment by hankinsoft** [comment]
Hi,
This is a library, not an application. In order to use it, you would need to create an app that uses the library and then install that app on your iPhone. Unfortunately, I don't have a sample project available, but you can add it to your project via [Carthage](https://github.com/Carthage/Carthage), then `@import FreeTDS` and use it similar to something like:

```
  /* Initialize the login params in the structure */
  DBSETLUSER(login, UID);
  DBSETLPWD(login, PWD);

  /* Now connect to the DB Server */
  if ((dbconn = dbopen(login, DBSERVER)) == NULL) {
    fprintf(stderr, "Could not connect to DB Server: %s\n", DBSERVER);
    return;
  }
```

**Comment by uokivan** [comment]
Dear @hankinsoft
Thank you very much,
I will try for it ,
That can help me find the way

Ivan
